pootle/apps/pootle_app/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2008 Zuza Software Foundation
#
# This file is part of translate.
#
# translate is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

from django.conf.urls import include, patterns

urlpatterns = patterns('',
    (r'^admin', include('pootle_app.views.admin.urls')),
    (r'', include('pootle_app.views.index.urls')),
)

pootle/apps/profiles/urls.py
"""
URLConf for Django user profile management.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/profiles/'.

If the default behavior of the profile views is acceptable to you,
simply use a line like this in your root URLConf to set up the default
URLs for profiles::

    (r'^profiles/', include('profiles.urls')),

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead. If you do, it's a
good idea to keep the name ``profiles_profile_detail`` for the pattern
which points to the ``profile_detail`` view, since several views use
``reverse()`` with that name to generate a default post-submission
redirect. If you don't use that name, remember to explicitly pass
``success_url`` to those views.

"""

from django.conf.urls.defaults import *

from profiles import views


urlpatterns = patterns('',
                       url(r'^create/?$',
                           views.create_profile,
                           name='profiles_create_profile'),
                       url(r'^edit/?$',
                           views.edit_profile,
                           name='profiles_edit_profile'),
                       url(r'^(?P<username>[^/]+)/?$',
                           views.profile_detail,
                           name='profiles_profile_detail'),
                       url(r'^$',
                           views.profile_list,
                           name='profiles_profile_list'),
                       )

pootle/apps/staticpages/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2012-2013 Zuza Software Foundation
#
# This file is part of Pootle.
#
# Pootle is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

from django.conf.urls import patterns, url

from .views import (AdminTemplateView, PageCreateView, PageDeleteView,
                    PageUpdateView)

urlpatterns = patterns('',
    url(r'^legal/agreement/$',
        'staticpages.views.legal_agreement',
        name='staticpages.legal-agreement'),
    url(r'^(?P<virtual_path>.+)/$',
        'staticpages.views.display_page',
        name='staticpages.display'),
)

admin_patterns = patterns('',
    url(r'^$',
        AdminTemplateView.as_view(),
        name='staticpages.admin'),

    url(r'^(?P<page_type>[^/]+)/add/?$',
        PageCreateView.as_view(),
        name='staticpages.create'),
    url(r'^(?P<page_type>[^/]+)/(?P<pk>\d+)/?$',
        PageUpdateView.as_view(),
        name='staticpages.edit'),
    url(r'^(?P<page_type>[^/]+)/(?P<pk>\d+)/delete/?$',
        PageDeleteView.as_view(),
        name='staticpages.delete'),
)

pootle/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2008-2012 Zuza Software Foundation
#
# This file is part of Pootle.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.conf.urls import include, patterns
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^django_admin/', include(admin.site.urls)),

    # JavaScript i18n
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
     {'packages': ('pootle', ), }, ),

    # XXX: Do we really want to let Django serve these files in production?
    # Direct download of translation files
    (r'^export/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.PODIRECTORY}, ),

    # External apps
    (r'^contact/', include('contact_form_i18n.urls')),
    (r'^accounts/', include('pootle_profile.urls')),
)

if settings.POOTLE_ENABLE_API:
    from api_factory import api_factory
    urlpatterns += patterns(
        '',
        # Pootle API URLs
        (r'^api/', include(api_factory().urls)),
    )

urlpatterns += patterns(
    '',
    # Pootle URLs
    (r'^pages/', include('staticpages.urls')),
    (r'', include('pootle_app.urls')),
    (r'^projects/', include('pootle_project.urls')),
    (r'', include('pootle_notifications.urls')),
    (r'', include('pootle_terminology.urls')),
    (r'', include('pootle_store.urls')),
    (r'', include('pootle_language.urls')),
    (r'', include('pootle_translationproject.urls')),
)

pootle/apps/contact_form_i18n/forms.py
"""
A base contact form for allowing users to send email messages through
a web interface, and a subclass demonstrating useful functionality.

"""


from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.template import loader
from django.template import RequestContext
from django.contrib.sites.models import Site
from django.utils.translation import ugettext_lazy as _


# I put this on all required fields, because it's easier to pick up
# on them with CSS or JavaScript if they have a class of "required"
# in the HTML. Your mileage may vary.
attrs_dict = { 'class': 'required' }


class ContactForm(forms.Form):
    """
    Base contact form class from which all contact form classes should
    inherit.

    If you don't need any custom functionality, you can simply use
    this form to provide basic contact functionality; it will collect
    name, email address and message.

    The ``contact_form`` view included in this application knows how
    to work with this form and can handle many types of subclasses as
    well (see below for a discussion of the important points), so in
    many cases it will be all that you need. If you'd like to use this
    form or a subclass of it from one of your own views, just do the
    following:

    1. When you instantiate the form, pass the current ``HttpRequest``
       object to the constructor as the keyword argument ``request``;
       this is used internally by the base implementation, and also
       made available so that subclasses can add functionality which
       relies on inspecting the request.

    2. To send the message, call the form's ``save`` method, which
       accepts the keyword argument ``fail_silently`` and defaults it
       to ``False``. This argument is passed directly to
       ``send_mail``, and allows you to suppress or raise exceptions
       as needed for debugging. The ``save`` method has no return
       value.

    Other than that, treat it like any other form; validity checks and
    validated data are handled normally, through the ``is_valid``
    method and the ``cleaned_data`` dictionary.


    Base implementation
    -------------------

    Under the hood, this form uses a somewhat abstracted interface in
    order to make it easier to subclass and add functionality. There
    are several important attributes subclasses may want to look at
    overriding, all of which will work (in the base implementation) as
    either plain attributes or as callable methods:

    * ``from_email`` -- used to get the address to use in the
      ``From:`` header of the message. The base implementation returns
      the value of the ``DEFAULT_FROM_EMAIL`` setting.

    * ``message`` -- used to get the message body as a string. The
      base implementation renders a template using the form's
      ``cleaned_data`` dictionary as context.

    * ``recipient_list`` -- used to generate the list of recipients
      for the message. The base implementation returns the email
      addresses specified in the ``MANAGERS`` setting.

    * ``subject`` -- used to generate the subject line for the
      message. The base implementation returns the string 'Message
      sent through the web site', with the name of the current
      ``Site`` prepended.

    * ``template_name`` -- used by the base ``message`` method to
      determine which template to use for rendering the
      message. Default is ``contact_form/contact_form.txt``.

    Internally, the base implementation ``_get_message_dict`` method
    collects ``from_email``, ``message``, ``recipient_list`` and
    ``subject`` into a dictionary, which the ``save`` method then
    passes directly to ``send_mail`` as keyword arguments.

    Particularly important is the ``message`` attribute, with its base
    implementation as a method which renders a template; because it
    passes ``cleaned_data`` as the template context, any additional
    fields added by a subclass will automatically be available in the
    template. This means that many useful subclasses can get by with
    just adding a few fields and possibly overriding
    ``template_name``.

    Much useful functionality can be achieved in subclasses without
    having to override much of the above; adding additional validation
    methods works the same as any other form, and typically only a few
    items -- ``recipient_list`` and ``subject_line``, for example,
    need to be overridden to achieve customized behavior.


    Other notes for subclassing
    ---------------------------

    Subclasses which want to inspect the current ``HttpRequest`` to
    add functionality can access it via the attribute ``request``; the
    base ``message`` takes advantage of this to use ``RequestContext``
    when rendering its template. See the ``AkismetContactForm``
    subclass in this file for an example of using the request to
    perform additional validation.

    Subclasses which override ``__init__`` need to accept ``*args``
    and ``**kwargs``, and pass them via ``super`` in order to ensure
    proper behavior.

    Subclasses should be careful if overriding ``_get_message_dict``,
    since that method **must** return a dictionary suitable for
    passing directly to ``send_mail`` (unless ``save`` is overridden
    as well).

    Overriding ``save`` is relatively safe, though remember that code
    which uses your form will expect ``save`` to accept the
    ``fail_silently`` keyword argument. In the base implementation,
    that argument defaults to ``False``, on the assumption that it's
    far better to notice errors than to silently not send mail from
    the contact form (see also the Zen of Python: "Errors should never
    pass silently, unless explicitly silenced").

    """
    def __init__(self, data=None, files=None, request=None, *args, **kwargs):
        if request is None:
            raise TypeError("Keyword argument 'request' must be supplied")
        super(ContactForm, self).__init__(data=data, files=files, *args, **kwargs)
        self.request = request

    name = forms.CharField(max_length=100,
                           widget=forms.TextInput(attrs=attrs_dict),
                           label=_('Your name'))
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=200)),
                             label=_('Your email address'))
    body = forms.CharField(widget=forms.Textarea(attrs=attrs_dict),
                              label=_('Your message'))

    recipient_list = [mail_tuple[1] for mail_tuple in settings.MANAGERS]

    subject_template_name = "contact_form/contact_form_subject.txt"

    template_name = 'contact_form/contact_form.txt'

    def from_email(self):
        return self.cleaned_data['email'] or settings.DEFAULT_FROM_EMAIL

    def message(self):
        """
        Render the body of the message to a string.

        """
        if callable(self.template_name):
            template_name = self.template_name()
        else:
            template_name = self.template_name
        return loader.render_to_string(template_name,
                                       self.get_context())

    def subject(self):
        """
        Render the subject of the message to a string.

        """
        subject = loader.render_to_string(self.subject_template_name,
                                          self.get_context())
        return ''.join(subject.splitlines())

    def get_context(self):
        """
        Return the context used to render the templates for the email
        subject and body.

        By default, this context includes:

        * All of the validated values in the form, as variables of the
          same names as their fields.

        * The current ``Site`` object, as the variable ``site``.

        * Any additional variables added by context processors (this
          will be a ``RequestContext``).

        """
        if not self.is_valid():
            raise ValueError("Cannot generate Context from invalid contact form")
        return RequestContext(self.request,
                              dict(self.cleaned_data,
                                   site=Site.objects.get_current()))

    def get_message_dict(self):
        """
        Generate the various parts of the message and return them in a
        dictionary, suitable for passing directly as keyword arguments
        to ``django.core.mail.send_mail()``.

        By default, the following values are returned:

        * ``from_email``

        * ``message``

        * ``recipient_list``

        * ``subject``

        """
        if not self.is_valid():
            raise ValueError("Message cannot be sent from invalid contact form")
        message_dict = {}
        for message_part in ('from_email', 'message', 'recipient_list', 'subject'):
            attr = getattr(self, message_part)
            message_dict[message_part] = callable(attr) and attr() or attr
        return message_dict

    def save(self, fail_silently=False):
        """
        Build and send the email message.

        """
        send_mail(fail_silently=fail_silently, **self.get_message_dict())


class AkismetContactForm(ContactForm):
    """
    Contact form which doesn't add any extra fields, but does add an
    Akismet spam check to the validation routine.

    Requires the setting ``AKISMET_API_KEY``, which should be a valid
    Akismet API key.

    """
    def clean_body(self):
        """
        Perform Akismet validation of the message.

        """
        if 'body' in self.cleaned_data and getattr(settings, 'AKISMET_API_KEY', ''):
            from akismet import Akismet
            from django.utils.encoding import smart_str
            akismet_api = Akismet(key=settings.AKISMET_API_KEY,
                                  blog_url='http://%s/' % Site.objects.get_current().domain)
            if akismet_api.verify_key():

pootle/apps/pootle_language/forms.py
# -*- coding: utf-8 -*-
#
# Copyright 2012 Zuza Software Foundation
#
# This file is part of Pootle.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

from django import forms

from pootle_language.models import Language

class DescriptionForm(forms.ModelForm):

    class Meta:
        model = Language
        fields = ("description", "specialchars")

pootle/templates/profiles/edit_personal.html
{% extends "user_profile_base_extended.html"  %}
{% load i18n %}
 
{% block title %}{% trans "Profile" %} | {{ block.super }}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}<li>{% trans "Profile" %}</li>
{% endblock %}

{% block body_id %}profile{% endblock %}

{% block section_description %}{% trans "Here you can change your personal details. This information will be used in the header of the translation files." %}{% endblock %}

{% block section_body %}
<form method="post" action="">
{% csrf_token %}
    <p>
        <label for="id_first_name">{% trans 'First Name' %}</label>
        {{ form.first_name }}
        {{ form.first_name.errors }}
    </p>
    <p>
        <label for="id_last_name">{% trans 'Last Name' %}</label>
        {{ form.last_name }}
        {{ form.last_name.errors }}
    </p>
    <p>
        <label for="id_email">{% trans 'Email address' %}</label>
        {{ form.email }}
        {{ form.email.errors }}
    </p>
    <p class="buttons">
        <input type="submit" class="save" value="{% trans 'Save' %}" />
    </p>
</form>
{% endblock %}

pootle/templates/profiles/edit_profile.html
{% extends "user_profile_base_extended.html"  %}
{% load assets i18n baseurl %}
 
{% block title %}{% trans "Translation Settings" %} | {{ block.super }}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}<li>{% trans "Translation Settings" %}</li>
{% endblock %}

{% block body_id %}settings{% endblock %}

{% block section_description %}{% trans "Here you can configure the settings related to the translation interface as well as your language preferences." %}{% endblock %}

{% block section_body %}
<form method="post" action="">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
  <p>{{ field.errors }}
    {{ field.label_tag }} {{ field }}
    {% if field.help_text %}<span class="help_text">{{ field.help_text }}</span>{% endif %}
  </p>
  {% endfor %}
  <p class="buttons">
      <input type="submit" class="save" value="{% trans 'Save' %} "/>
  </p>
</form>
{% endblock %}

{% block scripts_extra %}
{% endblock %}

pootle/templates/profiles/profile_detail.html
{% extends "user_profile_base.html"  %}
{% load i18n baseurl profile_tags %}

{% block title %}
{{ profile.user }} | {% trans "Users" %} | {{ settings.TITLE }}
{% endblock %}

{% block body_id %}dashboard{% endblock %}

{% block breadcrumbs %}
<li>{% trans "Users" %}</li><li>{{ profile.user }}</li>
{% endblock %}

{% block header_tabs_block %}
{% if user == profile.user %}
  {{ block.super }}
{% endif %}
{% endblock %}

{% block content %}
<div id="user-profile" class="module" lang="{{ LANGUAGE_CODE }}">
  <div class="hd">
    <h2>{% trans "Contributions" %}</h2>
  </div>
  <div class="bd">
    <div id="user-meta-wrapper">
      <div id="user-meta">
        <img src="{{ profile|gravatar:150 }}" width="150" height="150"{% if user == profile.user %} title="{% trans "You can set or change your avatar image at www.gravatar.com" %}"{% endif %} />
        <div class="user-name">{{ profile.user.username }}</div>
      </div>
    </div>
    <div id="user-contributions-wrapper">
      <div id="user-contributions">
        {% with contributions=profile.contributions %}
        {% if contributions %}
        {% for language, tp_user_stats in contributions %}
        <h3><a href="{{ language.get_absolute_url }}">{{ language.fullname }}</a></h3>
        <table id="user-contributions-{{ language.code }}" class="stats">
            <thead>
              <tr>
                <th>{% trans "Project" %}</th>
                <th class="number">{% trans "Suggestions Pending" %}</th>
                <th class="number">{% trans "Accepted" %}</th>
                <th class="number">{% trans "Rejected" %}</th>
                <th class="number">{% trans "Submissions" %}</th>
                <th class="number">{% trans "Overwritten" %}</th>
              </tr>
            </thead>
            <tbody>
            {% for tp, stats in tp_user_stats %}
              <tr class="item {% cycle 'even' 'odd' %}">
                <td><a href="{{ tp.get_absolute_url }}">{{ tp.project }}</a></td>
                {% for stat_item in stats %}
                {% if stat_item.count != 0 %}
                <td class="number"><a href="{{ stat_item.url }}">{{ stat_item.count }}</a></td>
                {% else %}
                <td></td>
                {% endif %}
                {% endfor %}
              </tr>
            {% endfor %}
            </tbody>
          </table>
        {% endfor %}
        {% else %}
        <h3>{% trans "This user doesn't have any contributions yet." %}</h3>
        {% endif %}
        {% endwith %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

pootle/templates/profiles/profile_list.html
{% extends "base.html"  %}
{% load i18n baseurl cleanhtml %}

{% block content %}

<div> 
    <p>{% trans "Profiles list" %}</p>
    
    <table border="0" cellpadding="5" cellspace="5" width="100%">
        <tr>
            <th>{% trans "Username" %}</th>
            <th>{% trans "First name" %}</th>
            <th>{% trans "Last name" %}</th>
        </tr>
        <tr><td colspan="4"><hr width="75%" align="left"></td></tr>
        {% for profile in object_list %}  
        <tr>
            <td><a href="{% filter l %}/accounts/{{ profile.user.username }}/{% endfilter %}">
                    {{ profile.user.username|obfuscate }}
            </a></td>
            <td>{{ profile.user.first_name }}</td>
            <td>{{ profile.user.last_name }} </td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}