pootle/apps/pootle_translationproject/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2008-2012 Zuza Software Foundation
# Copyright 2013 Evernote Corporation
#
# This file is part of Pootle.
#
# Pootle is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pootle is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pootle; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

from django.conf.urls import patterns, url


urlpatterns = patterns('pootle_translationproject.views',
    # Admin views
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/((.*/)*)admin_permissions.html$',
        'admin_permissions'),

    # Management actions
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/rescan/?$',
        'rescan_files',
        name='tp.rescan'),
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/update/?$',
        'update_against_templates',
        name='tp.update_against_templates'),
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/delete/(?P<dir_path>(.*/)*)(?P<filename>.*\.*)?$',
        'delete_path_obj',
        name='tp.delete_path_obj'),

    # VCS
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/'
        r'vcs-commit/(?P<dir_path>(.*/)*)(?P<filename>.*\.*)?$',
        'vcs_commit',
        name='pootle-vcs-commit'),
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/'
        r'vcs-update/(?P<dir_path>(.*/)*)(?P<filename>.*\.*)?$',
        'vcs_update',
        name='pootle-vcs-update'),

    # XHR views
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/((.*/)*)edit_settings.html$',
        'edit_settings'),
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/summary/(?P<dir_path>(.*/)*)(?P<filename>.*\.*)?$',
        'path_summary_more',
        name='tp.path_summary_more'),
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/ajax-add-tag/?$',
        'ajax_add_tag_to_tp',
        name='tp.ajax_add_tag'),
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/ajax-remove-tag/'
        r'(?P<tag_name>.*\.*)?$',
        'ajax_remove_tag_from_tp',
        name='tp.ajax_remove_tag'),

    # Exporting files
    (r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/(?P<file_path>.*)export/zip$',
        'export_zip'),

    # Translation
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/'
        r'translate/(?P<dir_path>(.*/)*)(?P<filename>.*\.*)?$',
        'translate',
        name='pootle-tp-translate'),

    # Export view for proofreading
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/'
        r'export-view/(?P<dir_path>(.*/)*)(?P<filename>.*\.*)?$',
        'export_view',
        name='export-view'),

    # Overview
    url(r'^(?P<language_code>[^/]*)/(?P<project_code>[^/]*)/(?P<dir_path>(.*/)*)(?P<filename>.*\.*)?$',
        'overview',
        name='pootle-tp-overview'),
)

pootle/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2008-2012 Zuza Software Foundation
#
# This file is part of Pootle.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.conf.urls import include, patterns
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^django_admin/', include(admin.site.urls)),

    # JavaScript i18n
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
     {'packages': ('pootle', ), }, ),

    # XXX: Do we really want to let Django serve these files in production?
    # Direct download of translation files
    (r'^export/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.PODIRECTORY}, ),

    # External apps
    (r'^contact/', include('contact_form_i18n.urls')),
    (r'^accounts/', include('pootle_profile.urls')),
)

if settings.POOTLE_ENABLE_API:
    from api_factory import api_factory
    urlpatterns += patterns(
        '',
        # Pootle API URLs
        (r'^api/', include(api_factory().urls)),
    )

urlpatterns += patterns(
    '',
    # Pootle URLs
    (r'^pages/', include('staticpages.urls')),
    (r'', include('pootle_app.urls')),
    (r'^projects/', include('pootle_project.urls')),
    (r'', include('pootle_notifications.urls')),
    (r'', include('pootle_terminology.urls')),
    (r'', include('pootle_store.urls')),
    (r'', include('pootle_language.urls')),
    (r'', include('pootle_translationproject.urls')),
)

pootle/apps/pootle_translationproject/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2010-2013 Zuza Software Foundation
#
# This file is part of Pootle.
#
# Pootle is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# Pootle is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Pootle; if not, see <http://www.gnu.org/licenses/>.

from django import forms
from django.utils.translation import ugettext as _

from pootle_app.models import Directory
from pootle_app.models.permissions import check_permission
from pootle_translationproject.models import TranslationProject


class DescriptionForm(forms.ModelForm):

    class Meta:
        model = TranslationProject
        fields = ("description",)


def upload_form_factory(request, current_path):
    translation_project = request.translation_project
    choices = []

    if check_permission('overwrite', request):
        choices.append(('overwrite', _("Overwrite the current file if it "
                                       "exists")))
    if check_permission('translate', request):
        choices.append(('merge', _("Merge the file with the current file and "
                                   "turn conflicts into suggestions")))
    if check_permission('suggest', request):
        choices.append(('suggest', _("Add all new translations as "
                                     "suggestions")))

    if check_permission('translate', request):
        initial = 'merge'
    else:
        initial = 'suggest'

    class StoreFormField(forms.ModelChoiceField):
        def label_from_instance(self, instance):
            return instance.pootle_path[len(current_path):]

    class DirectoryFormField(forms.ModelChoiceField):
        def label_from_instance(self, instance):
            return instance.pootle_path[len(translation_project.pootle_path):]

    class UploadForm(forms.Form):
        file = forms.FileField(required=True, label=_('File'))
        overwrite = forms.ChoiceField(
            required=True,
            widget=forms.RadioSelect,
            label='',
            choices=choices,
            initial=initial
        )
        upload_to = StoreFormField(
            required=False,
            label=_('Upload to'),
            queryset=translation_project.stores.filter(
                pootle_path__startswith=current_path),
            help_text=_("Optionally select the file you want to merge with. "
                        "If not specified, the uploaded file's name is used.")
        )
        upload_to_dir = DirectoryFormField(
            required=False,
            label=_('Upload to'),
            queryset=Directory.objects.filter(
                pootle_path__startswith=translation_project.pootle_path). \
                exclude(pk=translation_project.directory.pk),
            help_text=_("Optionally select the file you want to merge with. "
                        "If not specified, the uploaded file's name is used.")
        )

    return UploadForm

pootle/apps/pootle_translationproject/templates/translation_project/admin_permissions.html
{% extends "tp_base_admin.html" %}

{% load assets baseurl i18n %}

{% block title %}{% trans "Permissions" %} | {{ block.super }}{% endblock %}

{% block body_id %}tpadminpermissions{% endblock %}

{% block section_body %}
<div class="settings-container centered" lang="{{ LANGUAGE_CODE }}">
    <p class="info">{% trans "Below you can add, edit, and delete the permissions for this translation project." %}</p>
    <p class="help">
      {% trans "The user “nobody” refers to any user that is not logged in (an anonymous, unidentified user). The user “default” refers to the rights that all logged in users will have by default, unless other specific rights were assigned to them." %}
    </p>
    {% include "admin/admin_general.html" %}
</div>
{% endblock %}

{% block scripts_extra %}
{{ block.super }}
{% assets "js_admin" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock %}

pootle/apps/pootle_translationproject/templates/translation_project/export_view.html
{% load assets cleanhtml i18n locale store_tags %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" dir="{% locale_dir %}">
<head>
  <title>{% trans "Export View" %} | {{ project.fullname }} |
    {{ language.localname }} | Pootle</title>
  <style type="text/css">
    html {
      font-family: sans-serif;
      font-size: 15px;
      background-color: #fff;
      color: #130f30;
    }

    table,
    caption,
    th,
    td {
      margin: 0px;
    }
    table {
      border: 1px solid #e9e9e9;
      border-collapse: collapse;
      border-spacing: 0px;

      padding: 0px;

      width: 100%;
    }
    caption, th, td {
      border: 1px solid #d9d9d9;
      padding: 0.5em;
    }
    caption, th {
      line-height: 1;
    }
    caption {
      background-color: #eee;
      border-style: solid solid none;
      font-size: 1.2em;
      font-weight: bold;
    }
    caption span {
      font-size: 0.7em;
      font-weight: 300;
      vertical-align: middle;
    }
    th {
      background-color: #f8f8f8;
      font-weight: 300;
      text-align: center;
    }
    th#source,
    th#translation {
      width: 50%;
    }
    tbody {
      line-height: 1.6;
    }
    td {
      vertical-align: top;
    }
    tr.empty {
      text-align: center;
    }
    tr.separator {
      font-style: italic;
    }

    .unit-number {
      float: right;
      font-size: 0.7em;
      line-height: 1;
    }
    html[dir="rtl"] .unit-number {
      float: left;
    }
    .unit-context {
      font-size: 0.9em;
      font-style: italic;
      color: #666;
    }

    .highlight-escape {
      color: #8e44ad;
    }
    .highlight-html {
      color: #840;
    }
  </style>
</head>
<body>
  <table dir="{% locale_dir %}">
    <caption>{{ project.fullname }} / {{ language.localname }}
      {% if filter_name %} / {{ filter_name }}{% endif %}
      {% if filter_extra %}<span>({{ filter_extra|join:', ' }})</span>{% endif %}
    </caption>
    <thead>
      <tr lang="{{ LANGUAGE_CODE }}">
        <th id="source">{% trans "Source" %}</th>
        <th id="translation">{% trans "Translation" %}</th>
      </tr>
    </thead>
    <tbody>
    {% for path, units in unit_groups %}
      <tr class="separator">
        <th colspan="2">{{ path }}</th>
      </tr>
    {% for unit in units %}
      <tr{% if unit.isfuzzy %} class="unit-fuzzy"{% endif %}>
        <td>
        {% for i, source, title in unit|pluralize_source %}
          <div lang="{{ source_language.code }}"
            dir="{{ source_language.get_direction }}">
            {{ source|fancy_highlight }}
          </div>
        {% endfor %}
        {% if unit.getcontext %}
        <div class="unit-context">
          {{ unit.getcontext }}
        </div>
        {% endif %}
        </td>
        <td>
        {% for i, target, title in unit|pluralize_target %}
          <div dir="{{ language.get_direction }}" lang="{{ language.code }}">
            {{ target|fancy_highlight }}
          </div>
        {% endfor %}
        <div class="unit-number">
          <a href="{{ unit.get_translate_url }}">#{{ unit.id }}</a>
        </div>
        </td>
      </tr>
    {% endfor %}
    {% empty %}
      <tr class="empty">
        <td colspan="2">{% trans "No strings." %}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</body>
</html>

pootle/apps/pootle_translationproject/templates/translation_project/overview.html
{% extends "tp_base.html" %}
{% load assets baseurl cache cleanhtml i18n locale progressbar search translation_project_tags common_tags profile_tags %}
{% get_current_language as LANGUAGE_CODE %}

{% block body_id %}tpoverview{% endblock %}

{% block search %}{% render_search %}{% endblock %}

{% block content %}
<div class="module first">
  <div class="hd">
    <h2>
      {% cache settings.CACHE_TIMEOUT path_trail path_obj.id %}
      <span><a href="{{ translation_project.pootle_path|l }}">{{ project.code }}</a> / {{ path_obj|trail:"/" }}</span>
      {% endcache %}
      <a href="" id="js-toggle-tags" class="hide tags-aside tags-toggle">
        <i class="icon-tag"></i>
        <span id="js-toggle-tags-text">{% trans "Show tags" %}</span>
      </a>
    </h2>
  </div>
  <div id="path-summary" class="bd">
    <ul>
      {% for summary_item in path_summary %}
      <li>{{ summary_item|safe }}</li>
      {% endfor %}
    </ul>
    {% progressbar stats stats.total.words %}
    <div id="js-path-summary-more" data-loaded="false" data-collapsed="true">
    </div>
  </div>

  <div class="tags-bd">
    {% if can_edit and add_tag_form %}
    <a href="#js-add-tag-dialog" class="js-add-tag-popup js-tags tags-add">
      <i class="icon-tag-add"></i> {% trans "Add tag" %}
    </a>
    {% endif %}
    <ul class="js-tags tag-list">
      {% block tag_list %}
      {% include "translation_project/xhr_tags_list.html" %}
      {% endblock %}
    </ul>
    <br />
  </div>

  {% if table %}
  <div class="hd">
    <h2>{% trans "Files and Subfolders" %}</h2>
  </div>
  <div class="bd">
    <div class="files-subfolders" lang="{{ LANGUAGE_CODE }}">
      {% display_table table %}
    </div>
  </div>
  {% endif %}
</div>

<div class="module">
  {% if action_groups %}
  <div class="hd">
    <h2>{% trans "Actions" %}</h2>
  </div>
  <div id="overview-actions" class="bd">
    {% for action_group in action_groups %}
    <div id="overview-actions-{{ action_group.group }}"
         class="overview-actions-container{% if forloop.first %} first{% endif %}">
      <div class="overview-actions-group">{{ action_group.group_display }}</div>
      <div class="overview-actions-content">
        <ul>
        {% for action in action_group.actions %}
        <li class="{% cycle "odd" "even" %}">
          <a href="{{ action.href }}" title="{{ action.tooltip }}"
          {% if action.class %}class="{{ action.class }}"{% endif %}>
          <i class="{{ action.icon }}"></i> <span>{{ action.text }}</span></a>
        </li>
        {% endfor %}
        </ul>
      </div>
    </div>
    {% endfor %}
    {% if action_output %}
    <div id="overview-actions-output" class="bd">
      <p>{{ action_output }}</p>
    </div>
    {% endif %}
  </div>
  {% endif %}

  {% if translation_project.description or project.description or language.description or can_edit %}
  <div class="hd">
    <h2>{% trans "Description" %}</h2>
  </div>

  <div id="overview-description" class="bd">

    <div id="overview-description-tp"
      class="markup-body{% if can_edit %} js-ctx-meta-desc{% endif %}">
    {% if translation_project.description %}
      {{ translation_project.description }}
    {% else %}
      <p class="placeholder muted">{% trans "No description set." %}</p>
    {% endif %}
    {% if can_edit %}
      {% include "admin/edit_links.html" %}
    {% endif %}
    </div>
  {% if can_edit %}
    <div class="settings-container js-edit-ctx-meta-desc" style="display:none;">
      {% include "admin/general_settings_form.html" with form_action="edit_settings.html" %}
    </div>
  {% endif %}

    {% if project.description %}
    <a class="overview-description-toggle js-toggle" href="#overview-description-project">{% blocktrans with project.fullname as project %}{{ project }} project information{% endblocktrans %}</a>
    <div id="overview-description-project" class="markup-body hide">
      {{ project.description }}
    </div>
    {% endif %}

    {% if language.description %}
    <a class="overview-description-toggle js-toggle" href="#overview-description-language">{% blocktrans with language.name as language %}{{ language }} language information{% endblocktrans %}</a>
    <div id="overview-description-language" class="markup-body hide">
      {{ language.description }}
    </div>
    {% endif %}

  </div>
  {% endif %}
</div>

{% if upload_form %}
<div id="upload" class="form popup-inline mfp-hide" lang="{{ LANGUAGE_CODE }}">
  <h2>{% trans "Upload File" %}</h2>
  <form action="" method="post" class="upload" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in upload_form %}
    <p {% if field.help_text %}title="{{ field.help_text }}"{% endif %}>
      {{ field.label_tag }} {{ field }}
      {{ field.errors }}
    </p>
    {% endfor %}
    <p class="buttons">
      <input type="submit" value="{% trans 'Upload' %}" />
    </p>
  </form>
</div>
{% endif %}

{% if can_edit and add_tag_form %}
<div id="js-add-tag-dialog" class="form popup-inline mfp-hide" lang="{{ LANGUAGE_CODE }}">
  <h2>{% trans "Add tag" %}</h2>
  {% include "common/xhr_add_tag_form.html" %}
</div>
{% endif %}
{% endblock content %}

{% block postcontent %}
{% include "top_contributers_table.html" %}
{% endblock postcontent %}

{% block scripts_extra %}
{{ block.super }}
<script type="text/javascript">
$(function() {
  PTL.search.init();

  PTL.common.updateRelativeDates();
  setInterval(PTL.common.updateRelativeDates, 6e4);

{% if upload_form %}
  $("select#id_upload_to_dir").parent().hide();
  $("input#id_file").change(function() {
    if (/\.zip$/.test($(this).val())) {
      $("select#id_upload_to").parent().hide();
      $("select#id_upload_to_dir").parent().show();
    } else {
      $("select#id_upload_to_dir").parent().hide();
      $("select#id_upload_to").parent().show();
    }
  });
{% endif %}
});
</script>
{% if user.is_superuser or request.permissions.administrate %}
{% assets "js_admin" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endif %}
{% endblock %}

pootle/apps/pootle_translationproject/templates/translation_project/store_overview.html
{% extends "translation_project/overview.html" %}

{% block tag_list %}
  {% include "store/xhr_tags_list.html" %}
{% endblock %}

pootle/apps/pootle_translationproject/templates/translation_project/xhr-path_summary.html
{% load i18n locale %}
{% if trans_stats %}
<div class="hd">
  <h3><span>{% trans "Translation Statistics" %}</span></h3>
</div>
<div>
  <table class="stats" lang="{{ LANGUAGE_CODE }}" dir="{% locale_dir %}">
    <tbody>
      {% for item in trans_stats %}
      <tr class="item">
        <td class="stats-name">{{ item.title }}</td>
        <td class="stats-number">{{ item.words|safe }}</td>
        <td class="stats-number">{{ item.percentage }}</td>
        <td class="stats-number">{{ item.units }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}
{% if check_failures %}
<div class="hd">
  <h3><span>{% trans "Failing Checks" %}</span></h3>
</div>
<div>
{% for failure_category in check_failures %}
  <h4>{{ failure_category.display_name }}</h4>
  <table id="check-{{ failure_category.name }}" class="checks">
    <tr>
    {% for check in failure_category.checks %}
      <td class="check-name"><a href="{{ check.url }}">{{ check.display_name }}</a></td>
      <td class="check-count"><a href="{{ check.url }}">{{ check.count }}</a></td>
    {% if not forloop.counter0|divisibleby:2 %}
    </tr>
    <tr>
    {% endif %}
    {% endfor %}
    </tr>
  </table>
{% endfor %}
</div>
{% endif %}
{% if not trans_stats and not check_failures %}
<h3>{% trans "Nothing to show" %}</h3>
{% endif %}

pootle/apps/pootle_translationproject/templates/translation_project/xhr_tags_list.html
{% load url from future %}
      {% for tp_tag in tp_tags %}
      <li>
        <span class="tag">{{ tp_tag }}</span>{% if can_edit %}
        <a href="{% url 'tp.ajax_remove_tag' language.code project.code tp_tag.name %}"
          class="tag-remove"></a>{% endif %}
      </li>
      {% endfor %}